- name: Ensure NVM directory has correct permissions
  ansible.builtin.file:
    path: "{{ nvm_install_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure system-wide NVM sourcing
  ansible.builtin.blockinfile:
    create: true
    path: /etc/profile.d/nvm.sh
    marker: "# NVM global config {mark}"
    block: |
      export NVM_DIR="{{ nvm_install_path }}"
      [ -s "{{ nvm_install_path }}/nvm.sh" ] && \. "{{ nvm_install_path }}/nvm.sh"
      [ -s "{{ nvm_install_path }}/bash_completion" ] && \. "{{ nvm_install_path }}/bash_completion"

- name: Install nvm, node and npm
  ansible.builtin.include_role:
    name: stephdewit.nvm

- name: Get Installed Node.js Version Path
  ansible.builtin.shell: >
    . {{ nvm_install_path }}/nvm.sh && echo $(nvm which default | xargs dirname)
  args:
    executable: /bin/bash
  register: node_bin_path
  changed_when: false


- name: Install Gatsby CLI, yarn and corepack
  community.general.npm:
    name: "{{ item }}"
    global: true
    executable: "{{ node_bin_path.stdout }}/npm"
  loop: "{{ repo_global_npm_packages }}"
  tags: repo-gatsby
