---
- name: Install Gatsby CLI, yarn, and corepack globally
  become: true
  become_user: amosley
  community.general.npm:
    name: "{{ item }}"
    executable: "~/.nvm/versions/node/v22.14.0/bin"
    global: true
  loop: "{{ repo_global_npm_packages }}"
  tags: repo-gatsby
