---
- name: Install Gatsby CLI, yarn, and corepack
  become: true
  become_user: amosley
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install --global {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ repo_global_npm_packages }}"
  tags: repo-gatsby
