---
- name: Install nvm, node and npm
  ansible.builtin.include_role:
    name: ansible-role-nvm
  vars:
    nodejs_version: "22.14.0"

- name: Install Gatsby CLI, yarn, and corepack
  become: true
  become_user: amosley
  community.general.npm:
    name: "{{ item }}"
    executable: "~/.nvm/versions/node/v22.14.0/bin/npm"
    global: true
  loop: "{{ repo_global_npm_packages }}"
  tags: repo-gatsby
