- name: Ensure NVM directory has correct permissions
  ansible.builtin.file:
    path: "{{ nvm_install_path }}"
    state: directory
    owner: root
    group: root
    mode: '0757'

- name: Ensure system-wide NVM sourcing
  ansible.builtin.blockinfile:
    create: true
    path: /etc/profile.d/nvm.sh
    marker: "# NVM global config {mark}"
    block: |
      export NVM_DIR="{{ nvm_install_path }}"
      [ -s "{{ nvm_install_path }}/nvm.sh" ] && \. "{{ nvm_install_path }}/nvm.sh"
      [ -s "{{ nvm_install_path }}/bash_completion" ] && \. "{{ nvm_install_path }}/bash_completion"
    owner: root
    group: root
    mode: '0755'

- name: Set safe directory configuration for git
  ansible.builtin.shell: >
    git config --global --add safe.directory '*'

- name: Install nvm, node and npm
  become: true
  become_user: amosley
  ansible.builtin.include_role:
    name: stephdewit.nvm

- name: Explictly install the latest version of node.js and npm
  become: true
  become_user: amosley
  ansible.builtin.shell: |
    nvm install --lts
  args:
    creates: /usr/local/nvm/versions/node

- name: Get Installed Node.js Version Path
  become: true
  become_user: amosley
  ansible.builtin.shell: >
    echo $(which npm | xargs dirname)
  args:
    executable: /bin/bash
  register: node_bin_path
  changed_when: false

- name: Install Gatsby CLI, yarn and corepack
  become: true
  become_user: amosley
  community.general.npm:
    name: "{{ item }}"
    global: true
    executable: "{{ node_bin_path.stdout }}/npm"
  loop: "{{ repo_global_npm_packages }}"
  tags: repo-gatsby
