---
- name: Install Gatsby CLI, yarn, and corepack
  become: true
  become_user: amosley
  ansible.builtin.shell: |
    source ~/.bashrc && npm install --global {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ repo_global_npm_packages }}"
  tags: repo-gatsby
