---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"
  tags: common-configuration

- name: Update and upgrade system packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    state: present
  tags: common-configuration

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop: "{{ common_packages }}"
  tags: common-configuration
