---
- name: Configure Fail2Ban
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      banaction = iptables-multiport
    mode: preserve
  notify: Restart Fail2Ban
  tags: common-security

- name: Enable Fail2Ban service
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
  tags: common-security
