---
- name: Set hostname
  ansible.builtin.hostname:
    name: am-static-site

- name: Update and upgrade system packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    state: present

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - fail2ban
    - ufw
    - git
    - python3-pip
    - python3
    - cargo
    - nginx

- name: Configure Fail2Ban
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      banaction = iptables-multiport
    mode: preserve
  notify: Restart Fail2Ban

- name: Enable Fail2Ban service
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started

- name: Configure UFW rules
  community.general.ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - OpenSSH
    - 'Nginx Full'

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Install mdBook globally
  community.general.cargo:
    name: mdbook
    executable: /usr/local/bin/mdbook

- name: Install mdBook-generate-summary plugin globally
  community.general.cargo:
    name: mdbook-generate-summary
    executable: /usr/local/bin/mdbook-generate-summary

- name: Install mdBook-chapter-path plugin globally
  community.general.cargo:
    name: mdbook-chapter-path
    executable: /usr/local/bin/mdbook-chapter-path
