---
- name: Create directories for site and repository
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ git_username }}"
    group: "{{ git_username }}"
    mode: '0755'
  loop:
    - "{{ git_repo_path }}"
    - "{{ git_www_path }}"

- name: Initialize bare Git repository  # noqa: command-instead-of-module # Suppresses lint rule about using command module when a module is available
  ansible.builtin.command:
    cmd: git init --bare {{ git_repo_path }}
  args:
    creates: "{{ git_repo_path }}"

- name: Set ownership of the Git repository
  ansible.builtin.file:
    path: "{{ git_repo_path }}"
    state: directory
    owner: "{{ git_username }}"
    group: "{{ git_username }}"
    mode: '0755'

- name: Add Git post-receive hook
  ansible.builtin.copy:
    dest: "{{ git_repo_path }}/hooks/post-receive"
    content: |
      #!/bin/bash
      set -e
      GIT_REPO="{{ git_repo_path }}"
      WORK_TREE="{{ git_www_path }}"
      cd $GIT_REPO
      GIT_WORK_TREE=$WORK_TREE git checkout -f
      cd $WORK_TREE
      npm install --production
      npm run build
    mode: '0755'
    owner: "{{ git_username }}"
    group: "{{ git_username }}"
