---
- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: nginx-site-config.j2
    dest: /etc/nginx/sites-available/{{ nginx_domain }}
    owner: root
    group: root
    mode: '0644'

- name: Copy SSL certificate
  ansible.builtin.copy:
    content: "{{ lookup('env', 'CLOUDFLARE_CERT') }}"
    dest: "{{ nginx_ssl_cert_path }}/cloudflare.pem"
    owner: root
    group: root
    mode: '0644'

- name: Copy SSL private key
  ansible.builtin.copy:
    content: "{{ lookup('env', 'CLOUDFLARE_KEY') }}"
    dest: "{{ nginx_ssl_cert_path }}/cloudflare.key.pem"
    owner: root
    group: root
    mode: '0600'

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ nginx_domain }}
    dest: /etc/nginx/sites-enabled/{{ nginx_domain }}
    state: link
  notify: Restart Nginx
