---
- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: nginx-site-config.j2
    dest: /etc/nginx/sites-available/{{ domain }}
    owner: root
    group: root
    mode: '0644'

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ domain }}
    dest: /etc/nginx/sites-enabled/{{ domain }}
    state: link
  notify: Restart Nginx
