---
- name: Deploy Nginx configuration
  ansible.builtin.template:
    src: nginx-site-config.j2
    dest: /etc/nginx/sites-available/{{ nginx_domain }}
    owner: root
    group: root
    mode: '0644'

- name: Deploy Cloudflare SSL certificate
  ansible.builtin.copy:
    content: "{{ lookup('file', 'cloudflare_cert.pem') }}"
    dest: "{{ nginx_ssl_cert_path }}/cloudflare_cert.pem"
    owner: root
    group: root
    mode: '0644'

- name: Copy SSL private key
  ansible.builtin.copy:
    content: "{{ lookup('file', 'cloudflare_key.pem') }}"
    dest: "{{ nginx_ssl_cert_path }}/cloudflare_key.pem"
    owner: root
    group: root
    mode: '0600'

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ nginx_domain }}
    dest: /etc/nginx/sites-enabled/{{ nginx_domain }}
    state: link
  notify: Restart Nginx
