#cloud-config
# Creates the user ansible for configuration with ansible playbooks
name: ansible
groups: users, admin
sudo: ALL=(ALL) NOPASSWD:ALL
shell: /bin/bash
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINLo35q0WX/c3ulmxvLo8A9j2pmZHxIZiDwxYWQVaRib ansible@am-static-site

# Writes the ssh hardening config to a separate file for better management
write_files:
  path: /etc/ssh/sshd_config.d/hardening.conf
  content: |
    PermitRootLogin no
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    ChallengeResponseAuthentication no
    MaxAuthTries 2
    AllowTcpForwarding no
    X11Forwarding no
    AllowAgentForwarding no
    AuthorizedKeysFile .ssh/authorized_keys
    AllowUsers ${var.personal_user} ansible

# Webhook to call bootstrap-server workflow
# runcmd:
#   - >
#     curl -L \
#       -X POST \
#       -H "Accept: application/vnd.github+json" \
#       -H "Authorization: Bearer ${data.hcp_vault_secrets_secret.github_pa_token.secret_value}" \
#       -H "X-GitHub-Api-Version: 2022-11-28" \
#       https://api.github.com/repos/${var.repo_name}/actions/workflows/${var.workflow_id}/dispatches \
#       -d '{"event_type": "ready"}'