---
# Gatsby task variables
repo_global_npm_packages:
  - gatsby-cli
  - yarn
  - corepack

# Git task variables
repo_domain_name: ajmosley.com
repo_git_username: amosley
repo_git_repo_path: /var/repos/{{ repo_domain_name }}.git
repo_git_www_path: /var/www/{{ repo_domain_name }}
