#cloud-config
# Creates the user ansible for configuration with ansible playbooks
users:
- name: ansible
  groups: users, admin
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
    - ${ansible_user_ssh_key}

# Writes the ssh hardening config to a separate file for better management
write_files:
  - path: /etc/ssh/sshd_config.d/hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      MaxAuthTries 2
      AllowTcpForwarding no
      X11Forwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys
      AllowUsers ${personal_user} ansible
runcmd:
  - curl -fsSL https://tailscale.com/install.sh | sh
  - tailscale up --auth-key=${tailscale_tailnet_key} --ssh
  - TAILSCALE_IP=$(tailscale ip -4)
  - >
    curl \
      -X PUT \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer ${hcloud_api_token}" \
      "https://api.hetzner.cloud/v1/servers/${server_id}" \
      -d '{"labels":{"role":"webserver","ssh_ip":"${TAILSCALE_IP}"}}'
#   - >
#     curl -L \
#       -X POST \
#       -H "Accept: application/vnd.github+json" \
#       -H "Authorization: Bearer ${github_pa_token}" \
#       -H "X-GitHub-Api-Version: 2022-11-28" \
#       https://api.github.com/repos/${repo_name}/actions/workflows/${workflow_id}/dispatches \
#       -d '{"ref": "main"}'