---
- name: Include AWS credentials from vault
  ansible.builtin.include_vars:
    file: vault.yml
    name: aws_creds
  tags: website-aws

- name: Create AWS credentials directory
  ansible.builtin.file:
    path: ~/.aws
    state: directory
    mode: "0700"
  tags: website-aws

- name: Write AWS credentials to config file
  ansible.builtin.copy:
    dest: ~/.aws/config
    content: |
      [default]
      aws_access_key_id={{ aws_creds.vault_aws_access_key }}
      aws_secret_access_key={{ aws_creds.vault_aws_secret_key }}
    mode: "0600"
  tags: website-aws
