---
- name: Allow Certbot to trust plugins running as root (if not set)
  ansible.builtin.shell: |
    snap set certbot trust-plugin-with-root=ok
    touch /etc/certbot_plugin_set
  args:
    creates: /etc/certbot_plugin_set

- name: Install Certbot DNS Route53 plugin with snap module
  community.general.snap:
    name: certbot-dns-route53
    state: present

- name: Create aws settings folder
  ansible.builtin.file:
    path: ~/.aws
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Create Certbot config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: 'aws_config.j2', dest: '~/.aws/config' }
