---
- name: Install certbot
  community.general.snap:
    name:
      - certbot
    classic: true

- name: Install certbot-dns-route53
  community.general.snap:
    name:
      - certbot-dns-route53
    options:
      - trust-plugin-with-root=ok

- name: Create certbot settings folder
  ansible.builtin.file:
    path: /etc/letsencrypt/.aws
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Create Certbot config files
  ansible.builtin.template:
    src: ""
    dest: ""
    owner: root
    group: root
    mode: '0600'
  with_items:
    - { src: 'files/templates/aws_credentials.j2', dest: '/etc/letsencrypt/.aws/config'}
    - { src: 'files/templates/letsencrypt_cli.ini.j2', dest: '/etc/letsencrypt/cli.ini'}
