---
- name: Include AWS credentials from vault to get email address
  ansible.builtin.include_vars:
    file: vault.yml
    name: aws_creds

- name: Include geerlingguy.certbot role
  ansible.builtin.include_role:
    name: geerlingguy.certbot
    defaults_from: main
    vars_from: vault.yml
    vars:
      certbot_install_method: snap
      cerbbot_admin_email: "{{ aws_creds.vault_email_addres }}"
      certbot_create_if_missing: true
      certbot_create_standalone_stop_services: []
      certbot_certs:
        - domains:
            - "{{ domain_name }}"
      certbot_install_from_source: true
      certbot_auto_renew: true
      certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
      certbot_auto_renew_hour: "3"
      certbot_auto_renew_minute: "30"
      certbot_auto_renew_options: "--quiet"
