---
- name: Set plugin to have classic containment, then install it
  ansible.builtin.shell: |
    snap set certbot trust-plugin-with-root=ok
    snap install certbot-dns-route53

- name: Create aws settings folder
  ansible.builtin.file:
    path: ~/.aws
    state: directory
    owner: root
    group: root
    mode: '0700'


- name: Create certbot settings folder
  ansible.builtin.file:
    path: /etc/letsencrypt/.aws
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Create Certbot config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    # - { src: 'aws_config.j2', dest: '/etc/letsencrypt/.aws/config' }
    - { src: 'aws_config.j2', dest: '~/.aws/config' }
    # - { src: 'letsencrypt_cli.ini.j2', dest: '/etc/letsencrypt/cli.ini' }
