---
- name: Include geerlingguy.nginx role
  ansible.builtin.include_role:
    name: geerlingguy.nginx
    defaults_from: main
  vars:
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "{{ domain_name }}"
        root: "/var/www/{{ domain_name }}/public"
        index: "index index.html index.htm"
        state: "present"
        template: nginx_vhost.j2
        filename: "{{ domain_name }}.conf"
        extra_parameters: |
          ssl_certificate     {{ letsencrypt_cert_path }}/fullchain.pem;
          ssl_certificate_key {{ letsencrypt_cert_path }}/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
