---
- name: Create directories for site and repository
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: amosley
    group: amosley
    mode: '0755'
  loop:
    - "{{ repo_path }}"
    - "{{ www_path }}"

- name: Initialize bare Git repository
  ansible.builtin.git:
    repo: "{{ repo_path }}"
    bare: true

- name: Add Git post-receive hook
  ansible.builtin.copy:
    dest: "{{ repo_path }}/hooks/post-receive"
    content: |
      #!/bin/bash
      set -e
      GIT_WORK_TREE={{ www_path }} git checkout -f
      /root/.cargo/bin/mdbook build -d {{ www_path }}
    mode: '0755'
    owner: amosley
    group: amosley
