---
- name: Configure sudoers
  ansible.builtin.include_tasks: ../../bootstrap/tasks/configure_sudoers.yml
  vars:
    user_name: "{{ common_username }}"

- name: Check the OS family and configure as needed
  ansible.builtin.include_tasks: ../../bootstrap/tasks/install_sudo.yml

- name: Setup user with correct configuration
  ansible.builtin.include_tasks: ../../bootstrap/tasks/setup_user.yml
  vars:
    user_name: "{{ common_username }}"

- name: Set hostname, update/upgrade packages and install required packages
  ansible.builtin.include_tasks: basic_configuration.yml

- name: Configure UFW firewall
  ansible.builtin.include_tasks: configure_ufw.yml

- name: Configure Fail2Ban
  ansible.builtin.include_tasks: configure_fail2ban.yml
